"""LANGUAGE CLASSFICATION"""
DEFAULT_LANGUAGE = 1 # Current default language is Korean.
ENGLISH = 0
KOREAN = 1
ESPANOL = 2

"""ACTION TASKS"""
UNKNOWN_ERROR = -1
GREETING = 0
CLOCK = 1
TIMER = 2
JOKE = 3

HOUSE_PARTY_PROTOCOL = 999